import { useEffect, useState } from "react";
import { CheckCircle2, ClipboardList, Pencil, Plus, RefreshCw, Search, Trash2, UserCog, UserPlus } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { Input } from "../../components/ui/Input";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { Skeleton } from "../../components/ui/Skeleton";
import { listActivity } from "../../services/api/activityApi";
import type { ActivityItem } from "../../types/activity";
import { formatDate } from "../../utils/format";
import { Pagination } from "../Enquiries/Page";

const actionOptions = [{ value: "property.created", label: "Property created" }, { value: "property.updated", label: "Property updated" }, { value: "property.status_changed", label: "Property status changed" }, { value: "property.deleted", label: "Property deleted" }, { value: "enquiry.status_changed", label: "Enquiry status changed" }, { value: "enquiry.converted", label: "Enquiry converted" }, { value: "client.status_changed", label: "Client status changed" }];
const entityOptions = [{ value: "property", label: "Property" }, { value: "enquiry", label: "Enquiry" }, { value: "client", label: "Client" }];
const icons: Record<string, typeof Plus> = { "property.created": Plus, "property.updated": Pencil, "property.status_changed": RefreshCw, "property.deleted": Trash2, "enquiry.status_changed": ClipboardList, "enquiry.converted": UserPlus, "client.status_changed": UserCog };
function relative(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "Just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return formatDate(value); }
function entityLink(item: ActivityItem) { const path = item.entity.type === "property" ? `/properties/${item.entity.id}` : item.entity.type === "enquiry" ? `/enquiries/${item.entity.id}` : item.entity.type === "client" ? `/clients/${item.entity.id}` : null; return path ? <Link to={path} className="text-xs font-bold text-land-plum hover:underline">View {item.entity.type}</Link> : null; }

export default function ActivityPage() { const [input, setInput] = useState(""); const [search, setSearch] = useState(""); const [entity, setEntity] = useState<"" | "property" | "enquiry" | "client">(""); const [action, setAction] = useState<ActivityItem["action"] | "">(""); const [page, setPage] = useState(1); const [items, setItems] = useState<ActivityItem[]>([]); const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
 useEffect(() => { const timer = window.setTimeout(() => { setSearch(input); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [input]); const load = () => { const controller = new AbortController(); setLoading(true); setError(false); listActivity({ page, limit: 20, search, entity_type: entity || undefined, action: action || undefined }, controller.signal).then((response) => { if (!controller.signal.aborted) { setItems(response.activities); setPagination(response.pagination); } }).catch(() => !controller.signal.aborted && setError(true)).finally(() => !controller.signal.aborted && setLoading(false)); return controller; }; useEffect(() => { const controller = load(); return () => controller.abort(); }, [page, search, entity, action]); const clear = () => { setInput(""); setSearch(""); setEntity(""); setAction(""); setPage(1); }; const filtered = Boolean(input || entity || action);
 return <div className="mx-auto w-full max-w-5xl space-y-6"><PageHeader eyebrow="INSIGHTS" title="Recent Activity" description="A chronological record of important Admin operations."/><Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_180px_220px_auto]"><Input aria-label="Search activity" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Search activity" leftIcon={<Search size={17}/>}/><Select aria-label="Filter entity" value={entity} onChange={(event) => { setEntity(event.target.value as typeof entity); setPage(1); }} options={entityOptions} placeholder="All entities"/><Select aria-label="Filter action" value={action} onChange={(event) => { setAction(event.target.value as typeof action); setPage(1); }} options={actionOptions} placeholder="All actions"/>{filtered ? <Button variant="ghost" onClick={clear}>Clear</Button> : null}</div><div className="mt-7">{loading ? <div className="space-y-6">{[0,1,2,3].map((value) => <div className="flex gap-4" key={value}><Skeleton className="h-10 w-10 shrink-0 rounded-xl"/><div className="flex-1 space-y-2"><Skeleton className="h-5 w-4/5"/><Skeleton className="h-4 w-2/5"/></div></div>)}</div> : error ? <EmptyState title="Unable to load activity" description="Please try again shortly." action={<Button onClick={load}>Retry</Button>}/> : items.length === 0 ? <EmptyState title="No recent activity" description={filtered ? "No activity matches the selected filters." : "Important Admin operations will appear here."} action={filtered ? <Button variant="secondary" onClick={clear}>Clear filters</Button> : undefined}/> : <><ol className="relative space-y-6 before:absolute before:bottom-4 before:left-5 before:top-4 before:w-px before:bg-land-ink/[0.08]">{items.map((item) => { const Icon = icons[item.action] || CheckCircle2; return <li key={item.id} className="relative flex gap-4"><span className="z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-land-ink/[0.07] bg-white text-land-plum"><Icon size={18}/></span><article className="min-w-0 flex-1 rounded-xl border border-land-ink/[0.07] bg-white p-4 transition-shadow hover:shadow-[0_8px_24px_rgba(25,23,36,0.06)]"><div className="flex flex-wrap items-start justify-between gap-2"><p className="font-semibold text-land-ink">{item.description}</p><time className="text-xs font-semibold text-land-ink/45">{relative(item.created_at)}</time></div><div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-land-ink/55"><span>{item.actor ? `${item.actor.name} · ${item.actor.role}` : "System"}</span><span aria-hidden="true">·</span><span className="capitalize">{item.entity.type}</span>{entityLink(item)}</div></article></li>; })}</ol><Pagination pagination={pagination} onPage={setPage}/></>}</div></Card></div>; }
