import { useEffect, useState } from "react";
import { ArrowLeft, Mail, Phone } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Badge, type BadgeVariant } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card, CardHeader } from "../../components/ui/Card";
import { ConfirmDialog } from "../../components/ui/ConfirmDialog";
import { EmptyState } from "../../components/ui/EmptyState";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { getClient, updateClientStatus } from "../../services/api/clientsApi";
import type { Client, ClientStatus } from "../../types/client";
import { formatDate } from "../../utils/format";
const options = [{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }, { value: "suspended", label: "Suspended" }]; const badges: Record<ClientStatus, BadgeVariant> = { active: "success", inactive: "neutral", suspended: "danger" };
export default function ClientDetailPage() { const { clientId = "" } = useParams(); const [client, setClient] = useState<Client | null>(null); const [status, setStatus] = useState<ClientStatus>("active"); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [error, setError] = useState(false); const [confirm, setConfirm] = useState(false); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState("");
 const load = () => { const controller = new AbortController(); setLoading(true); getClient(clientId, controller.signal).then((response) => { if (!controller.signal.aborted) { setClient(response.client); setStatus(response.client.status); } }).catch((err: { status?: number }) => { if (!controller.signal.aborted) { setNotFound(err.status === 404); setError(err.status !== 404); } }).finally(() => !controller.signal.aborted && setLoading(false)); return controller; }; useEffect(() => { const controller = load(); return () => controller.abort(); }, [clientId]); const save = async () => { if (!client) return; setSaving(true); setActionError(""); try { await updateClientStatus(client.id, status); await getClient(client.id).then((response) => { setClient(response.client); setStatus(response.client.status); }); setConfirm(false); } catch { setActionError("Unable to update client status. Please try again."); } finally { setSaving(false); } };
 if (loading) return <div className="mx-auto max-w-[1440px]"><Card className="h-72 animate-pulse bg-land-stone"/></div>; if (notFound) return <EmptyState title="Client not found" description="This Seller/Client may no longer be available." action={<Link to="/clients"><Button>Back to clients</Button></Link>}/>; if (error || !client) return <EmptyState title="Unable to load client" description="Please try again shortly." action={<Button onClick={load}>Retry</Button>} />;
 return <div className="mx-auto w-full max-w-[1440px] space-y-6"><Link to="/clients" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-land-ink/65 hover:text-land-plum"><ArrowLeft size={17}/>Back to clients</Link><PageHeader eyebrow="SELLER / CLIENT" title={client.name} description={`Joined ${formatDate(client.created_at)}`}/><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><h2 className="font-display text-2xl">Contact & account</h2><p className="text-sm text-land-ink/60">Seller/Client account details.</p></CardHeader><dl className="grid gap-5 sm:grid-cols-2"><Field icon={<Mail size={17}/>} label="Email" value={client.email}/><Field icon={<Phone size={17}/>} label="Phone" value={client.phone || "Not provided"}/><Field label="Email verification" value={client.is_email_verified ? "Verified" : "Not verified"}/><Field label="Phone verification" value={client.is_phone_verified ? "Verified" : "Not verified"}/><Field label="Last login" value={formatDate(client.last_login_at)}/><Field label="Password setup" value={client.force_password_change ? "Password update required" : "Complete"}/></dl><div className="mt-7 border-t border-land-ink/[0.07] pt-5"><h3 className="font-display text-xl">Properties</h3><p className="mt-2 text-sm text-land-ink/60">No associated-property data is exposed by the current admin API.</p></div></Card><Card><CardHeader><h2 className="font-display text-2xl">Account status</h2><Badge variant={badges[client.status]} dot>{client.status}</Badge></CardHeader><Select label="Update account access" value={status} onChange={(event) => setStatus(event.target.value as ClientStatus)} options={options}/>{actionError ? <p role="alert" className="mt-3 text-sm font-medium text-land-coral">{actionError}</p> : null}<Button className="mt-4 w-full" disabled={status === client.status} onClick={() => setConfirm(true)}>Save status</Button></Card></div><ConfirmDialog open={confirm} busy={saving} onCancel={() => setConfirm(false)} onConfirm={save} title="Change client account status?" confirmLabel="Update status" description="This affects the Seller/Client’s access to their account. You can change the status again later."/></div>; }
function Field({ icon, label, value }: { icon?: React.ReactNode; label: string; value: string }) { return <div><dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-land-ink/45">{icon}{label}</dt><dd className="mt-1.5 break-words text-sm font-semibold text-land-ink">{value}</dd></div>; }
