import { useEffect, useState } from "react";
import { ArrowLeft, Mail, MapPin, Phone } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Badge, type BadgeVariant } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card, CardHeader } from "../../components/ui/Card";
import { ConfirmDialog } from "../../components/ui/ConfirmDialog";
import { EmptyState } from "../../components/ui/EmptyState";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { getEnquiry, updateEnquiryStatus } from "../../services/api/enquiriesApi";
import type { Enquiry, EnquiryStatus, UpdateEnquiryStatusResponse } from "../../types/enquiry";
import { formatDate } from "../../utils/format";

const options = [{ value: "new", label: "New" }, { value: "reviewed", label: "Reviewed" }, { value: "converted", label: "Converted" }, { value: "rejected", label: "Rejected" }];
const badge: Record<EnquiryStatus, BadgeVariant> = { new: "success", reviewed: "info", converted: "premium", rejected: "danger" };

export default function EnquiryDetailPage() {
  const { enquiryId = "" } = useParams(); const [enquiry, setEnquiry] = useState<Enquiry | null>(null); const [status, setStatus] = useState<EnquiryStatus>("new"); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [error, setError] = useState(false); const [confirm, setConfirm] = useState(false); const [saving, setSaving] = useState(false); const [result, setResult] = useState<UpdateEnquiryStatusResponse | null>(null); const [actionError, setActionError] = useState("");
  const load = () => { const controller = new AbortController(); setLoading(true); setError(false); getEnquiry(enquiryId, controller.signal).then((response) => { if (!controller.signal.aborted) { setEnquiry(response.enquiry); setStatus(response.enquiry.status); } }).catch((err: { status?: number }) => { if (!controller.signal.aborted) { setNotFound(err.status === 404); setError(err.status !== 404); } }).finally(() => !controller.signal.aborted && setLoading(false)); return controller; };
  useEffect(() => { const controller = load(); return () => controller.abort(); }, [enquiryId]);
  const save = async () => { if (!enquiry) return; setSaving(true); setActionError(""); try { const response = await updateEnquiryStatus(enquiry.id, { status, rejection_remark: status === "rejected" ? "Rejected by administrator" : undefined }); setResult(response); await getEnquiry(enquiry.id).then((next) => { setEnquiry(next.enquiry); setStatus(next.enquiry.status); }); setConfirm(false); } catch { setActionError("Unable to update this enquiry. Please try again."); } finally { setSaving(false); } };
  if (loading) return <div className="mx-auto max-w-[1440px]"><Card className="h-72 animate-pulse bg-land-stone"/></div>;
  if (notFound) return <EmptyState title="Enquiry not found" description="This enquiry may have been removed or the link is invalid." action={<Link to="/enquiries"><Button>Back to enquiries</Button></Link>}/>;
  if (error || !enquiry) return <EmptyState title="Unable to load enquiry" description="Please try again shortly." action={<Button onClick={load}>Retry</Button>} />;
  return <div className="mx-auto w-full max-w-[1440px] space-y-6"><Link to="/enquiries" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-land-ink/65 hover:text-land-plum"><ArrowLeft size={17}/>Back to enquiries</Link><PageHeader eyebrow="ENQUIRY" title={enquiry.name} description={`Received ${formatDate(enquiry.created_at)}`}/><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><h2 className="font-display text-2xl">Enquiry Overview</h2><p className="text-sm text-land-ink/60">Customer details and requirements.</p></CardHeader><dl className="grid gap-5 sm:grid-cols-2"><Info icon={<Phone size={17}/>} label="Phone" value={enquiry.phone}/><Info icon={<Mail size={17}/>} label="Email" value={enquiry.email || "Not provided"}/><Info icon={<MapPin size={17}/>} label="Location" value={enquiry.city || "Not provided"}/><Info label="Intent" value={enquiry.intent || "Not specified"}/><Info label="Property type" value={enquiry.property_type || "Not specified"}/><Info label="Last updated" value={formatDate(enquiry.updated_at)}/></dl><div className="mt-7 border-t border-land-ink/[0.07] pt-5"><p className="text-xs font-bold uppercase tracking-wide text-land-ink/45">Message</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-land-ink/75">{enquiry.message || "No message was provided."}</p></div>{enquiry.rejection_remark ? <div className="mt-5 rounded-xl border border-land-coral/20 bg-land-coral/[0.06] p-4 text-sm text-land-ink/70"><strong className="text-land-coral">Rejection note:</strong> {enquiry.rejection_remark}</div> : null}</Card><div className="space-y-6"><Card><CardHeader><h2 className="font-display text-2xl">Status</h2><Badge variant={badge[enquiry.status]} dot>{enquiry.status}</Badge></CardHeader><Select label="Update status" value={status} onChange={(event) => setStatus(event.target.value as EnquiryStatus)} options={options}/>{actionError ? <p role="alert" className="mt-3 text-sm font-medium text-land-coral">{actionError}</p> : null}<Button className="mt-4 w-full" disabled={status === enquiry.status} onClick={() => setConfirm(true)}>Save status</Button></Card>{result?.seller ? <Card><CardHeader><h2 className="font-display text-2xl">Conversion complete</h2></CardHeader><p className="text-sm text-land-ink/65">Seller account: {result.seller.email}</p><p className="mt-2 text-xs text-land-ink/45">A related property was provisioned through the existing conversion workflow.</p></Card> : null}</div></div><ConfirmDialog open={confirm} busy={saving} onCancel={() => setConfirm(false)} onConfirm={save} confirmLabel={status === "converted" ? "Convert enquiry" : "Update status"} title={status === "converted" ? "Convert this enquiry?" : "Update enquiry status?"} description={status === "converted" ? "This will provision the Seller/Client and related property through LANDLOGY’s existing secure conversion workflow." : `Change this enquiry to ${status}.`}/></div>;
}
function Info({ icon, label, value }: { icon?: React.ReactNode; label: string; value: string }) { return <div><dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-land-ink/45">{icon}{label}</dt><dd className="mt-1.5 break-words text-sm font-semibold text-land-ink">{value}</dd></div>; }
