import { useEffect, useState } from "react";
import { Eye, Search, X } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge, type BadgeVariant } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { Input } from "../../components/ui/Input";
import { PageHeader } from "../../components/ui/PageHeader";
import { Select } from "../../components/ui/Select";
import { Skeleton } from "../../components/ui/Skeleton";
import { listEnquiries } from "../../services/api/enquiriesApi";
import type { EnquiryListItem, EnquiryStatus } from "../../types/enquiry";
import { formatDate } from "../../utils/format";

const statusOptions = [{ value: "new", label: "New" }, { value: "reviewed", label: "Reviewed" }, { value: "converted", label: "Converted" }, { value: "rejected", label: "Rejected" }];
const badge: Record<EnquiryStatus, BadgeVariant> = { new: "success", reviewed: "info", converted: "premium", rejected: "danger" };
const label: Record<EnquiryStatus, string> = { new: "New", reviewed: "Reviewed", converted: "Converted", rejected: "Rejected" };

export default function EnquiriesPage() {
  const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState<EnquiryStatus | "">(""); const [page, setPage] = useState(1);
  const [items, setItems] = useState<EnquiryListItem[]>([]); const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(searchInput); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [searchInput]);
  const load = () => { const controller = new AbortController(); setLoading(true); setError(false); listEnquiries({ page, limit: 20, search, status: status || undefined }, controller.signal).then((response) => { if (!controller.signal.aborted) { setItems(response.enquiries); setPagination(response.pagination); } }).catch(() => !controller.signal.aborted && setError(true)).finally(() => !controller.signal.aborted && setLoading(false)); return controller; };
  useEffect(() => { const controller = load(); return () => controller.abort(); }, [page, search, status]);
  const clear = () => { setSearchInput(""); setSearch(""); setStatus(""); setPage(1); };
  const hasFilters = Boolean(searchInput || status);
  const content = loading ? <RowsSkeleton /> : error ? <EmptyState title="Unable to load enquiries" description="Please try again shortly." action={<Button onClick={load}>Retry</Button>} /> : items.length === 0 ? <EmptyState title={hasFilters ? "No enquiries match your search" : "No enquiries yet"} description={hasFilters ? "Try clearing or adjusting the filters." : "Customer enquiries will appear here as they arrive."} action={hasFilters ? <Button variant="secondary" onClick={clear}>Clear filters</Button> : undefined} /> : <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-land-ink/[0.07] text-xs uppercase tracking-wide text-land-ink/45"><tr><th className="px-1 py-3">Enquiry</th><th className="px-3 py-3">Location</th><th className="px-3 py-3">Intent</th><th className="px-3 py-3">Property type</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th><th className="px-1 py-3 text-right">Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-land-ink/[0.06] last:border-0 hover:bg-land-stone/60"><td className="px-1 py-4"><p className="font-semibold text-land-ink">{item.name}</p><p className="mt-0.5 text-xs text-land-ink/55">{item.phone}{item.email ? ` · ${item.email}` : ""}</p></td><td className="px-3 py-4 text-sm text-land-ink/70">{item.city || "—"}</td><td className="px-3 py-4 text-sm text-land-ink/70">{item.intent || "—"}</td><td className="px-3 py-4 text-sm text-land-ink/70">{item.property_type || "—"}</td><td className="px-3 py-4"><Badge variant={badge[item.status]} dot>{label[item.status]}</Badge></td><td className="px-3 py-4 text-sm text-land-ink/55">{formatDate(item.created_at)}</td><td className="px-1 py-4 text-right"><Link to={`/enquiries/${item.id}`} className="inline-flex min-h-11 items-center gap-1 rounded-xl px-3 text-sm font-bold text-land-plum hover:bg-land-pearl"><Eye size={16}/>View</Link></td></tr>)}</tbody></table></div><div className="space-y-3 lg:hidden">{items.map((item) => <article key={item.id} className="rounded-xl border border-land-ink/[0.07] p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-land-ink">{item.name}</p><p className="mt-1 text-sm text-land-ink/60">{item.phone}</p></div><Badge variant={badge[item.status]} dot>{label[item.status]}</Badge></div><p className="mt-3 text-sm text-land-ink/65">{[item.city, item.intent, item.property_type].filter(Boolean).join(" · ") || "No additional details"}</p><div className="mt-3 flex items-center justify-between text-xs text-land-ink/50"><span>{formatDate(item.created_at)}</span><Link to={`/enquiries/${item.id}`} className="min-h-11 pt-2 font-bold text-land-plum">View enquiry</Link></div></article>)}</div><Pagination pagination={pagination} onPage={setPage}/></>;
  return <div className="mx-auto w-full max-w-[1440px] space-y-6"><PageHeader eyebrow="LEADS" title="Enquiries" description="Manage and review customer enquiries and conversion activity."/><Card><div className="flex flex-col gap-3 sm:flex-row"><Input aria-label="Search enquiries" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Search name, email or phone" leftIcon={<Search size={17}/>} rightElement={searchInput ? <button aria-label="Clear search" onClick={() => setSearchInput("")} className="text-land-ink/45 hover:text-land-ink"><X size={16}/></button> : undefined}/><Select aria-label="Filter by status" value={status} onChange={(event) => { setStatus(event.target.value as EnquiryStatus | ""); setPage(1); }} options={statusOptions} placeholder="All statuses" className="sm:max-w-48"/>{hasFilters ? <Button variant="ghost" onClick={clear}>Clear</Button> : null}</div><div className="mt-5">{content}</div></Card></div>;
}

function RowsSkeleton() { return <div className="space-y-3">{[0,1,2,3,4].map((item) => <div key={item} className="flex gap-4 border-b border-land-ink/[0.06] py-3"><Skeleton className="h-10 flex-1"/><Skeleton className="hidden h-10 w-24 sm:block"/><Skeleton className="h-10 w-20"/></div>)}</div>; }
export function Pagination({ pagination, onPage }: { pagination: { page: number; limit: number; total: number; totalPages: number }; onPage: (page: number) => void }) { const start = pagination.total ? (pagination.page - 1) * pagination.limit + 1 : 0; const end = Math.min(pagination.page * pagination.limit, pagination.total); return <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-land-ink/[0.06] pt-4 text-sm text-land-ink/60"><span>Showing {start}–{end} of {pagination.total}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={pagination.page <= 1} onClick={() => onPage(pagination.page - 1)}>Previous</Button><Button size="sm" variant="secondary" disabled={pagination.page >= pagination.totalPages} onClick={() => onPage(pagination.page + 1)}>Next</Button></div></div>; }
